name: minerl
channels:
  - pytorch
  - conda-forge
  - defaults
dependencies:
  - python=3.7
  - pip
  - py-opencv
  - cudatoolkit=10.2
  - pip:
    - git+https://github.com/minerllabs/minerl
    - coloredlogs
    - matplotlib
    - aicrowd-api
    - aicrowd-gym
    - gym3
    - attrs
    - torch==1.12.1
    - torchvision==0.13.1
    - pandas==0.23.4
    - PyYAML>=5.3.1
    - numpy>=1.18.5
    - Pillow>=7.1.2
    - requests>=2.23.0
    - scipy>=1.4.1
    - tqdm>=4.64.0
    - seaborn>=0.11.0
    - ipython
    - psutil
    - thop>=0.1.1
    - jsonlines
